### ISSUE TITLE
Change the packageName to something more specific

### ISSUE THREAD

**Issue by rnhurt** [JamieH/godaddy-domainclient#1]
I would like to suggest changing the package name to "godaddyapi" instead of "swagger".  I'm working on adding GoDaddy to the [dnscontrol](https://github.com/StackExchange/dnscontrol) project and it would make it easier to add this package if the name was more descriptive.  Plus, if there are other Swagger built APIs added in the future using something other than "swagger" would be beneficial.

I was going to create a pull request for this issue but I thought it would be better to ask first. 😄 

NOTE: I've tried recreating this project but can't get certain models to generate (Domains, Orders, Subscriptions, etc.) while other models work fine.  There are no errors or warnings, it just doesn't generate them.   Do you remember the configuration you used to generate this project?

**Comment by j-mie** [comment]
Hi there,

Feel free to submit PRs this to, I don't think I ever tested it though :(

I'm sorry I don't remember the configuration I used, I think I might of modified Swagger to get it to work in the end :(

**Comment by rnhurt** [comment]
Actually, I tried working with this code and it didn't really work at all.  I'm working with the [swagger-codegen project](https://github.com/swagger-api/swagger-codegen/issues/6832) to see if I can get a clean conversion so that we don't have to have this project.  Or at least it's easier to generate and update.  :)

I'll submit a PR if/when I get something.

**Comment by j-mie** [comment]
@rnhurt just wanted to let you know I've renamed the package.
