### ISSUE TITLE
How to use RecordAdd?

### ISSUE THREAD

**Issue by igroykt** [JamieH/godaddy-domainclient#2]
Hello.
RecordAdd require ArrayOfDnsRecord, but it looks like there is no way to cast DnsRecord into ArrayOfDnsRecord.
Tried to use in this way:
```go
var conv interface{} = dataSet
var record godaddy.ArrayOfDnsRecord = conv.(godaddy.ArrayOfDnsRecord)
_, err = apiClient.V1Api.RecordAdd(ctx, domain, record, nil)
```
But it is not work (panic: interface conversion: interface {} is godaddy.DnsRecord, not godaddy.ArrayOfDnsRecord).
Thank.

**Comment by j-mie** [comment]
Try using v1.0.0, I regenerated the API using a more competent code generator, it looks like it just takes an array of DNS records now.

**Comment by igroykt** [comment]
Hello.
Updated to v1.0.0 and things get worse. Docs are broken in the readme, RecordAdd return another type and I was unable to find a description of it struct.
So I decided to fallback to v0.1.0 and modify ArrayOfDnsRecord model:
```go
type ArrayOfDnsRecord interface {}
```
And now it works as expected:
```go
func addRecord(domain string, data string, name string, recordType string) (bool, error) {
	var err error
	dataSet := godaddy.DnsRecord{
		Data:     data,
		Name:     name,
		Port:     0,
		Priority: 0,
		Protocol: "",
		Service:  "",
		Ttl:      int32(3600),
		Type_:    recordType,
		Weight:   0,
	}
	record := []interface{}{dataSet}
	_, err = apiClient.V1Api.RecordAdd(ctx, domain, record, nil)
	if err != nil {
		return false, err
	}
	return true, err
}
```
Anyway, thank for help.
